branches:
  except:
    - gh-pages
language: perl
perl:
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
before_install: 
  - cpanm Dist::Zilla && dzil authordeps --missing | cpanm
script: "dzil build && dzil test"
